@php
    $detail = $employee->administrativeDetail ?? new \App\Models\EmployeeAdministrativeDetail();
    $taxStatuses = \App\Models\EmployeeAdministrativeDetail::TAX_STATUSES;
    $bpjsStatuses = \App\Models\EmployeeAdministrativeDetail::BPJS_STATUSES;
    $ptkpStatuses = \App\Models\EmployeeAdministrativeDetail::PTKP_STATUSES;
    $display = fn ($value) => filled($value) ? $value : 'Belum diisi';
    $nikTaxValue = old('nik_used_as_tax_id', is_null($detail->nik_used_as_tax_id) ? '' : ($detail->nik_used_as_tax_id ? '1' : '0'));
@endphp
<div class="alert alert-light-primary">Data ini bersifat sensitif dan hanya digunakan untuk administrasi kepegawaian. Data dapat dilengkapi secara bertahap.</div>
@if ($editable)
<form method="POST" action="{{ route('pegawai.profile.administrative-details.update') }}" data-wizard-form>
    @csrf @method('PUT')
    <div class="card"><div class="card-header"><h5 class="mb-0">Rekening Bank</h5></div><div class="card-body"><div class="row g-3">
        <div class="col-md-6"><label for="bank_name" class="form-label">Nama Bank</label><input id="bank_name" name="bank_name" type="text" value="{{ old('bank_name', $detail->bank_name) }}" maxlength="100" class="form-control @error('bank_name') is-invalid @enderror">@error('bank_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="bank_account_number" class="form-label">Nomor Rekening</label><input id="bank_account_number" name="bank_account_number" type="text" value="{{ old('bank_account_number', $detail->bank_account_number) }}" maxlength="30" inputmode="numeric" autocomplete="off" class="form-control @error('bank_account_number') is-invalid @enderror">@error('bank_account_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label for="bank_account_holder" class="form-label">Nama Pemilik Rekening</label><input id="bank_account_holder" name="bank_account_holder" type="text" value="{{ old('bank_account_holder', $detail->bank_account_holder) }}" maxlength="255" class="form-control"></div>
    </div></div></div>
    <div class="card"><div class="card-header"><h5 class="mb-0">Perpajakan</h5></div><div class="card-body"><div class="row g-3">
        <div class="col-md-6"><label for="tax_status" class="form-label">Status Pajak</label><select id="tax_status" name="tax_status" class="form-select @error('tax_status') is-invalid @enderror"><option value="">Belum dipilih</option>@foreach ($taxStatuses as $value => $label)<option value="{{ $value }}" @selected(old('tax_status', $detail->tax_status) === $value)>{{ $label }}</option>@endforeach</select>@error('tax_status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="tax_identification_number" class="form-label">Nomor Identitas Pajak</label><input id="tax_identification_number" name="tax_identification_number" type="text" value="{{ old('tax_identification_number', $detail->tax_identification_number) }}" maxlength="24" inputmode="numeric" autocomplete="off" class="form-control @error('tax_identification_number') is-invalid @enderror">@error('tax_identification_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="nik_used_as_tax_id" class="form-label">NIK Digunakan sebagai Identitas Pajak</label><select id="nik_used_as_tax_id" name="nik_used_as_tax_id" class="form-select"><option value="">Belum dijawab</option><option value="1" @selected((string) $nikTaxValue === '1')>Ya</option><option value="0" @selected((string) $nikTaxValue === '0')>Tidak</option></select></div>
        <div class="col-md-6"><label for="ptkp_status" class="form-label">Status PTKP</label><select id="ptkp_status" name="ptkp_status" class="form-select @error('ptkp_status') is-invalid @enderror"><option value="">Belum dipilih</option>@foreach ($ptkpStatuses as $status)<option value="{{ $status }}" @selected(old('ptkp_status', $detail->ptkp_status) === $status)>{{ $status }}</option>@endforeach</select>@error('ptkp_status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div></div></div>
    <div class="card"><div class="card-header"><h5 class="mb-0">BPJS</h5></div><div class="card-body"><div class="row g-3">
        <div class="col-md-6"><label for="bpjs_health_status" class="form-label">Status BPJS Kesehatan</label><select id="bpjs_health_status" name="bpjs_health_status" class="form-select @error('bpjs_health_status') is-invalid @enderror"><option value="">Belum dipilih</option>@foreach ($bpjsStatuses as $value => $label)<option value="{{ $value }}" @selected(old('bpjs_health_status', $detail->bpjs_health_status) === $value)>{{ $label }}</option>@endforeach</select>@error('bpjs_health_status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="bpjs_health_number" class="form-label">Nomor BPJS Kesehatan</label><input id="bpjs_health_number" name="bpjs_health_number" type="text" value="{{ old('bpjs_health_number', $detail->bpjs_health_number) }}" maxlength="20" inputmode="numeric" autocomplete="off" class="form-control @error('bpjs_health_number') is-invalid @enderror">@error('bpjs_health_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="bpjs_employment_status" class="form-label">Status BPJS Ketenagakerjaan</label><select id="bpjs_employment_status" name="bpjs_employment_status" class="form-select @error('bpjs_employment_status') is-invalid @enderror"><option value="">Belum dipilih</option>@foreach ($bpjsStatuses as $value => $label)<option value="{{ $value }}" @selected(old('bpjs_employment_status', $detail->bpjs_employment_status) === $value)>{{ $label }}</option>@endforeach</select>@error('bpjs_employment_status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="bpjs_employment_number" class="form-label">Nomor KPJ/BPJS Ketenagakerjaan</label><input id="bpjs_employment_number" name="bpjs_employment_number" type="text" value="{{ old('bpjs_employment_number', $detail->bpjs_employment_number) }}" maxlength="20" inputmode="numeric" autocomplete="off" class="form-control @error('bpjs_employment_number') is-invalid @enderror">@error('bpjs_employment_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div></div></div>
    <div class="d-flex flex-wrap justify-content-between gap-2"><a href="{{ route('pegawai.profile.wizard.show', 'education') }}" class="btn btn-light-secondary"><i class="ti ti-arrow-left"></i> Kembali</a><div class="d-flex flex-wrap gap-2"><button name="wizard_action" value="stay" class="btn btn-outline-primary" type="submit">Simpan Draft</button><button name="wizard_action" value="next" class="btn btn-primary" type="submit">Simpan &amp; Lanjutkan <i class="ti ti-arrow-right"></i></button></div></div>
</form>
@else
<div class="card"><div class="card-header"><h5 class="mb-0">Data Administrasi</h5></div><div class="card-body"><div class="row">
    <div class="col-md-6 mb-3"><small class="text-muted d-block">Nama Bank</small>{{ $display($detail->bank_name) }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Nomor Rekening</small>{{ $display($detail->masked_bank_account_number) }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Status Pajak</small>{{ $detail->tax_status ? ($taxStatuses[$detail->tax_status] ?? $detail->tax_status) : 'Belum diisi' }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Nomor Pajak</small>{{ $display($detail->masked_tax_identification_number) }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Status BPJS Kesehatan</small>{{ $detail->bpjs_health_status ? ($bpjsStatuses[$detail->bpjs_health_status] ?? $detail->bpjs_health_status) : 'Belum diisi' }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Nomor BPJS Kesehatan</small>{{ $display($detail->masked_bpjs_health_number) }}</div><div class="col-md-6"><small class="text-muted d-block">Status BPJS Ketenagakerjaan</small>{{ $detail->bpjs_employment_status ? ($bpjsStatuses[$detail->bpjs_employment_status] ?? $detail->bpjs_employment_status) : 'Belum diisi' }}</div><div class="col-md-6"><small class="text-muted d-block">Nomor KPJ</small>{{ $display($detail->masked_bpjs_employment_number) }}</div>
</div></div></div>
<div class="d-flex justify-content-between gap-2"><a href="{{ route('pegawai.profile.wizard.show', 'education') }}" class="btn btn-light-secondary"><i class="ti ti-arrow-left"></i> Kembali</a><a href="{{ route('pegawai.profile.wizard.show', 'review') }}" class="btn btn-primary">Lanjutkan <i class="ti ti-arrow-right"></i></a></div>
@endif
