@php $display = fn ($value) => filled($value) ? $value : 'Belum diisi'; @endphp
<div class="card">
    <div class="card-header"><h5 class="mb-1">Kontak dan Alamat</h5><p class="mb-0 text-muted">Email pribadi tidak mengubah email akun login.</p></div>
    <div class="card-body">
        @if ($editable)
            <form method="POST" action="{{ route('pegawai.profile.wizard.contact-address.update') }}" data-wizard-form>
                @csrf @method('PUT')
                <div class="row g-3">
                    <div class="col-md-6"><label for="phone" class="form-label">Nomor HP</label><input id="phone" name="phone" type="text" value="{{ old('phone', $employee->phone) }}" maxlength="30" class="form-control @error('phone') is-invalid @enderror">@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-6"><label for="whatsapp_number" class="form-label">Nomor WhatsApp</label><input id="whatsapp_number" name="whatsapp_number" type="text" value="{{ old('whatsapp_number', $employee->whatsapp_number) }}" maxlength="30" class="form-control @error('whatsapp_number') is-invalid @enderror">@error('whatsapp_number')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-check mt-2"><input id="same_as_phone" type="checkbox" class="form-check-input"><label for="same_as_phone" class="form-check-label">Sama dengan nomor HP</label></div></div>
                    <div class="col-12"><label for="email" class="form-label">Email Pribadi</label><input id="email" name="email" type="email" value="{{ old('email', $employee->email) }}" maxlength="255" class="form-control @error('email') is-invalid @enderror">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-12"><label for="identity_address" class="form-label">Alamat Sesuai KTP</label><textarea id="identity_address" name="identity_address" rows="3" maxlength="2000" class="form-control @error('identity_address') is-invalid @enderror">{{ old('identity_address', $employee->identity_address) }}</textarea>@error('identity_address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-12"><div class="form-check"><input type="hidden" name="domicile_same_as_identity" value="0"><input id="domicile_same_as_identity" name="domicile_same_as_identity" value="1" type="checkbox" class="form-check-input" @checked((bool) old('domicile_same_as_identity', $employee->domicile_same_as_identity))><label for="domicile_same_as_identity" class="form-check-label">Alamat domisili sama dengan alamat KTP</label></div></div>
                    <div class="col-12"><label for="address" class="form-label">Alamat Domisili</label><textarea id="address" name="address" rows="3" maxlength="2000" class="form-control @error('address') is-invalid @enderror">{{ old('address', $employee->address) }}</textarea>@error('address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-6"><label for="domicile_province" class="form-label">Provinsi</label><input id="domicile_province" name="domicile_province" type="text" value="{{ old('domicile_province', $employee->domicile_province) }}" maxlength="100" class="form-control"></div>
                    <div class="col-md-6"><label for="domicile_city" class="form-label">Kabupaten/Kota</label><input id="domicile_city" name="domicile_city" type="text" value="{{ old('domicile_city', $employee->domicile_city) }}" maxlength="100" class="form-control"></div>
                    <div class="col-md-6"><label for="domicile_district" class="form-label">Kecamatan</label><input id="domicile_district" name="domicile_district" type="text" value="{{ old('domicile_district', $employee->domicile_district) }}" maxlength="100" class="form-control"></div>
                    <div class="col-md-6"><label for="domicile_village" class="form-label">Kelurahan/Desa</label><input id="domicile_village" name="domicile_village" type="text" value="{{ old('domicile_village', $employee->domicile_village) }}" maxlength="100" class="form-control"></div>
                    <div class="col-md-6"><label for="domicile_postal_code" class="form-label">Kode Pos</label><input id="domicile_postal_code" name="domicile_postal_code" type="text" value="{{ old('domicile_postal_code', $employee->domicile_postal_code) }}" maxlength="5" inputmode="numeric" class="form-control @error('domicile_postal_code') is-invalid @enderror">@error('domicile_postal_code')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                </div>
                <div class="d-flex flex-wrap justify-content-between gap-2 mt-4"><a href="{{ route('pegawai.profile.wizard.show', 'identification') }}" class="btn btn-light-secondary"><i class="ti ti-arrow-left"></i> Kembali</a><div class="d-flex flex-wrap gap-2"><button name="wizard_action" value="stay" class="btn btn-outline-primary" type="submit">Simpan Draft</button><button name="wizard_action" value="next" class="btn btn-primary" type="submit">Simpan &amp; Lanjutkan <i class="ti ti-arrow-right"></i></button></div></div>
            </form>
        @else
            <div class="row"><div class="col-md-6 mb-3"><small class="text-muted d-block">Nomor HP</small>{{ $display($employee->phone) }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Nomor WhatsApp</small>{{ $display($employee->whatsapp_number) }}</div><div class="col-12 mb-3"><small class="text-muted d-block">Email Pribadi</small>{{ $display($employee->email) }}</div><div class="col-12 mb-3"><small class="text-muted d-block">Alamat Sesuai KTP</small>{{ $display($employee->identity_address) }}</div><div class="col-12"><small class="text-muted d-block">Alamat Domisili</small>{{ $display($employee->address) }}</div></div>
            <div class="mt-4"><a href="{{ route('pegawai.profile.wizard.show', 'identification') }}" class="btn btn-light-secondary"><i class="ti ti-arrow-left"></i> Kembali</a></div>
        @endif
    </div>
</div>
