@php
    $genderLabels = ['male' => 'Laki-laki', 'female' => 'Perempuan'];
    $religionLabels = ['islam' => 'Islam', 'kristen' => 'Kristen', 'katolik' => 'Katolik', 'hindu' => 'Hindu', 'buddha' => 'Buddha', 'konghucu' => 'Konghucu'];
    $maritalLabels = ['single' => 'Belum Menikah', 'married' => 'Menikah', 'divorced' => 'Cerai Hidup', 'widowed' => 'Cerai Mati'];
    $mask = fn ($value) => filled($value) ? str_repeat('*', max(strlen($value) - 4, 0)).substr($value, -4) : 'Belum diisi';
    $display = fn ($value) => filled($value) ? $value : 'Belum diisi';
@endphp
<div class="card">
    <div class="card-header"><h5 class="mb-1">Identitas Pribadi</h5><p class="mb-0 text-muted">Data identitas dapat disimpan secara bertahap.</p></div>
    <div class="card-body">
        @if ($editable)
            <form method="POST" action="{{ route('pegawai.profile.wizard.identification.update') }}" enctype="multipart/form-data" data-wizard-form>
                @csrf @method('PUT')
                <div class="row g-3">
                    <div class="col-md-6"><label for="full_name" class="form-label">Nama Lengkap</label><input id="full_name" name="full_name" type="text" value="{{ old('full_name', $employee->full_name) }}" class="form-control @error('full_name') is-invalid @enderror" required>@error('full_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-6"><label for="nik" class="form-label">NIK</label><input id="nik" name="nik" type="text" value="{{ old('nik', $employee->nik) }}" maxlength="16" inputmode="numeric" autocomplete="off" class="form-control @error('nik') is-invalid @enderror">@error('nik')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-6"><label for="family_card_number" class="form-label">Nomor Kartu Keluarga</label><input id="family_card_number" name="family_card_number" type="text" value="{{ old('family_card_number', $employee->family_card_number) }}" maxlength="16" inputmode="numeric" autocomplete="off" class="form-control @error('family_card_number') is-invalid @enderror">@error('family_card_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-6"><label for="birth_place" class="form-label">Tempat Lahir</label><input id="birth_place" name="birth_place" type="text" value="{{ old('birth_place', $employee->birth_place) }}" maxlength="100" class="form-control @error('birth_place') is-invalid @enderror">@error('birth_place')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-6"><label for="birth_date" class="form-label">Tanggal Lahir</label><input id="birth_date" name="birth_date" type="date" value="{{ old('birth_date', $employee->birth_date?->format('Y-m-d')) }}" class="form-control @error('birth_date') is-invalid @enderror">@error('birth_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-6"><label for="gender" class="form-label">Jenis Kelamin</label><select id="gender" name="gender" class="form-select @error('gender') is-invalid @enderror"><option value="">Belum dipilih</option>@foreach ($genderLabels as $value => $label)<option value="{{ $value }}" @selected(old('gender', $employee->gender) === $value)>{{ $label }}</option>@endforeach</select>@error('gender')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-6"><label for="religion" class="form-label">Agama</label><select id="religion" name="religion" class="form-select @error('religion') is-invalid @enderror"><option value="">Belum dipilih</option>@foreach ($religionLabels as $value => $label)<option value="{{ $value }}" @selected(old('religion', $employee->religion) === $value)>{{ $label }}</option>@endforeach</select>@error('religion')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-6"><label for="marital_status" class="form-label">Status Perkawinan</label><select id="marital_status" name="marital_status" class="form-select @error('marital_status') is-invalid @enderror"><option value="">Belum dipilih</option>@foreach ($maritalLabels as $value => $label)<option value="{{ $value }}" @selected(old('marital_status', $employee->marital_status) === $value)>{{ $label }}</option>@endforeach</select>@error('marital_status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-6"><label for="nationality" class="form-label">Kewarganegaraan</label><input id="nationality" name="nationality" type="text" value="{{ old('nationality', $employee->nationality) }}" maxlength="100" class="form-control @error('nationality') is-invalid @enderror">@error('nationality')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-6"><label for="blood_type" class="form-label">Golongan Darah</label><select id="blood_type" name="blood_type" class="form-select @error('blood_type') is-invalid @enderror"><option value="">Belum dipilih</option>@foreach (['A','B','AB','O'] as $bloodType)<option value="{{ $bloodType }}" @selected(old('blood_type', $employee->blood_type) === $bloodType)>{{ $bloodType }}</option>@endforeach</select>@error('blood_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-12"><label for="photo" class="form-label">Pas Foto</label><input id="photo" name="photo" type="file" accept="image/*" class="form-control @error('photo') is-invalid @enderror"><div class="form-text">Kosongkan jika tidak ingin mengganti foto. Maksimal 2 MB.</div>@error('photo')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                </div>
                <div class="d-flex flex-wrap justify-content-end gap-2 mt-4"><button name="wizard_action" value="stay" class="btn btn-outline-primary" type="submit">Simpan Draft</button><button name="wizard_action" value="next" class="btn btn-primary" type="submit">Simpan &amp; Lanjutkan <i class="ti ti-arrow-right"></i></button></div>
            </form>
        @else
<div class="row g-4"><div class="col-md-6"><small class="text-muted d-block mb-1">Nama Lengkap</small>{{ $employee->full_name }}</div><div class="col-md-6"><small class="text-muted d-block mb-1">NIK</small>{{ $employee->masked_nik ?? 'Belum diisi' }}</div><div class="col-md-6"><small class="text-muted d-block mb-1">Nomor Kartu Keluarga</small>{{ $mask($employee->family_card_number) }}</div><div class="col-md-6"><small class="text-muted d-block mb-1">Tempat, Tanggal Lahir</small>{{ $display($employee->birth_place) }}, {{ $employee->birth_date?->format('d M Y') ?? 'Belum diisi' }}</div><div class="col-md-6"><small class="text-muted d-block mb-1">Jenis Kelamin</small>{{ $genderLabels[$employee->gender] ?? 'Belum diisi' }}</div><div class="col-md-6"><small class="text-muted d-block mb-1">Agama</small>{{ $religionLabels[$employee->religion] ?? 'Belum diisi' }}</div><div class="col-md-6"><small class="text-muted d-block mb-1">Status Perkawinan</small>{{ $maritalLabels[$employee->marital_status] ?? 'Belum diisi' }}</div><div class="col-md-6"><small class="text-muted d-block mb-1">Kewarganegaraan</small>{{ $display($employee->nationality) }}</div></div>
        @endif
    </div>
</div>
