@php
    $display = fn ($value) => filled($value) ? $value : 'Belum diisi';
    $mask = fn ($value) => filled($value) ? str_repeat('*', max(strlen($value) - 4, 0)).substr($value, -4) : 'Belum diisi';
    $detail = $employee->administrativeDetail;
    $highestEducation = $employee->educations->firstWhere('is_highest', true);
    $taxLabels = \App\Models\EmployeeAdministrativeDetail::TAX_STATUSES;
    $bpjsLabels = \App\Models\EmployeeAdministrativeDetail::BPJS_STATUSES;
    $employeeTypes = ['guru' => 'Guru', 'dosen' => 'Dosen', 'tenaga_kependidikan' => 'Tenaga Kependidikan', 'staff_yayasan' => 'Staff Yayasan', 'security' => 'Security', 'cleaning_service' => 'Cleaning Service', 'driver' => 'Driver', 'teknisi' => 'Teknisi'];
@endphp
<div class="alert alert-light-primary"><i class="ti ti-info-circle me-1"></i> Pengiriman profil untuk verifikasi akan tersedia setelah bagian dokumen dilengkapi.</div>

<div class="card"><div class="card-header"><h5 class="mb-0">Informasi Kepegawaian</h5></div><div class="card-body"><div class="row"><div class="col-md-6 mb-3"><small class="text-muted d-block">NUP / Nomor Pegawai</small>{{ $employee->formatted_employee_number }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Unit Kerja</small>{{ $employee->institution?->name ?? 'Belum diisi' }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Jabatan</small>{{ $employee->position?->name ?? 'Belum diisi' }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Jenis Pegawai</small>{{ $employeeTypes[$employee->employee_type] ?? $employee->employee_type }}</div><div class="col-md-6"><small class="text-muted d-block">Status Kerja</small>{{ $employee->employment_status }}</div></div></div></div>

<div class="card"><div class="card-header"><h5 class="mb-0">Identitas</h5></div><div class="card-body"><div class="row"><div class="col-md-6 mb-3"><small class="text-muted d-block">Nama Lengkap</small>{{ $employee->full_name }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">NIK</small>{{ $mask($employee->nik) }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Nomor Kartu Keluarga</small>{{ $mask($employee->family_card_number) }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Tempat, Tanggal Lahir</small>{{ $display($employee->birth_place) }}, {{ $employee->birth_date?->format('d M Y') ?? 'Belum diisi' }}</div></div></div></div>

<div class="card"><div class="card-header"><h5 class="mb-0">Kontak dan Alamat</h5></div><div class="card-body"><div class="row"><div class="col-md-6 mb-3"><small class="text-muted d-block">Nomor HP</small>{{ $display($employee->phone) }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Nomor WhatsApp</small>{{ $display($employee->whatsapp_number) }}</div><div class="col-12 mb-3"><small class="text-muted d-block">Email Pribadi</small>{{ $display($employee->email) }}</div><div class="col-12 mb-3"><small class="text-muted d-block">Alamat Sesuai KTP</small>{{ $display($employee->identity_address) }}</div><div class="col-12"><small class="text-muted d-block">Alamat Domisili</small>{{ $display($employee->address) }}</div></div></div></div>

<div class="card"><div class="card-header"><h5 class="mb-0">Keluarga</h5></div><div class="card-body"><div class="row mb-3"><div class="col-md-6"><small class="text-muted d-block">Kontak Darurat</small>{{ $display($employee->emergency_contact_name) }}</div><div class="col-md-6"><small class="text-muted d-block">Nomor Kontak</small>{{ $display($employee->emergency_contact_phone) }}</div></div><p class="mb-2"><strong>{{ $employee->familyMembers->count() }}</strong> anggota keluarga tersimpan.</p>@if ($employee->familyMembers->isNotEmpty())<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Nama</th><th>Hubungan</th><th>NIK</th></tr></thead><tbody>@foreach ($employee->familyMembers as $member)<tr><td>{{ $member->full_name }}</td><td>{{ $member->relationship_label }}</td><td>{{ $member->masked_nik }}</td></tr>@endforeach</tbody></table></div>@endif</div></div>

<div class="card"><div class="card-header"><h5 class="mb-0">Pendidikan dan Kompetensi</h5></div><div class="card-body"><div class="row"><div class="col-md-6 mb-3"><small class="text-muted d-block">Pendidikan Tertinggi</small>{{ $highestEducation ? $highestEducation->education_level_label.' - '.$highestEducation->institution_name : 'Belum diisi' }}@if ($highestEducation)<small class="text-muted d-block">Ijazah: {{ $highestEducation->masked_certificate_number }}</small>@endif</div><div class="col-md-3 mb-3"><small class="text-muted d-block">Riwayat Pendidikan</small>{{ $employee->educations->count() }}</div><div class="col-md-3 mb-3"><small class="text-muted d-block">Sertifikasi</small>{{ $employee->certifications->count() }}</div></div>@if ($employee->certifications->isNotEmpty())<ul class="mb-0">@foreach ($employee->certifications as $certification)<li>{{ $certification->name }} - {{ $certification->masked_certificate_number }}</li>@endforeach</ul>@endif</div></div>

<div class="card"><div class="card-header"><h5 class="mb-0">Administrasi</h5></div><div class="card-body"><div class="row"><div class="col-md-6 mb-3"><small class="text-muted d-block">Bank</small>{{ $display($detail?->bank_name) }} - {{ $display($detail?->masked_bank_account_number) }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">Status Pajak</small>{{ $detail?->tax_status ? ($taxLabels[$detail->tax_status] ?? $detail->tax_status) : 'Belum diisi' }}<small class="text-muted d-block">Nomor: {{ $display($detail?->masked_tax_identification_number) }}</small></div><div class="col-md-6 mb-3"><small class="text-muted d-block">BPJS Kesehatan</small>{{ $detail?->bpjs_health_status ? ($bpjsLabels[$detail->bpjs_health_status] ?? $detail->bpjs_health_status) : 'Belum diisi' }} - {{ $display($detail?->masked_bpjs_health_number) }}</div><div class="col-md-6 mb-3"><small class="text-muted d-block">BPJS Ketenagakerjaan</small>{{ $detail?->bpjs_employment_status ? ($bpjsLabels[$detail->bpjs_employment_status] ?? $detail->bpjs_employment_status) : 'Belum diisi' }} - {{ $display($detail?->masked_bpjs_employment_number) }}</div></div></div></div>

<div class="card"><div class="card-header"><h5 class="mb-0">Checklist Kelengkapan Sementara</h5></div><div class="card-body">
    @php $hasMissing = collect($profileProgress['sections'])->contains(fn ($section) => $section['missing'] !== []); @endphp
    @if (! $hasMissing)<div class="alert alert-success mb-0">Lima bagian data sementara sudah lengkap.</div>@else
        @foreach ($profileProgress['sections'] as $section) @if ($section['missing'] !== [])<div class="mb-3"><strong class="d-block mb-1">{{ $section['label'] }}</strong><ul class="mb-0">@foreach ($section['missing'] as $missing)<li>{{ $missing }}</li>@endforeach</ul></div>@endif @endforeach
    @endif
    <p class="text-muted mb-0 mt-3">Dokumen dan persyaratan submit akan ditambahkan pada tahap berikutnya.</p>
</div></div>

<div class="d-flex flex-wrap justify-content-between gap-2"><a href="{{ route('pegawai.profile.wizard.show', 'administration') }}" class="btn btn-light-secondary"><i class="ti ti-arrow-left"></i> Kembali</a><a href="{{ route('pegawai.profile.show') }}" class="btn btn-primary">Kembali ke Profil</a></div>
